### ISSUE TITLE
Push Jobs Server return error 400 when clients trying to get configs from server

### ISSUE THREAD

**Issue by yolcatl** [opscode-cookbooks/push-jobs#44]
Just installed Open Source Chef 12.1.2 and latest Push Jobs Server on CentOS 6.5 with latest clients on some Windows and CentOS 6.5 nodes. On each node I'm getting this output when I try to run pushy-client (suppose, problem like this present when I trying to start client as service):
```
[root@mynode chef]# /opt/opscode-push-jobs-client/embedded/bin/ruby /opt/opscode-push-jobs-client/bin/pushy-client -c /etc/chef/push-jobs-client.rb
INFO: [mynode] Using node name: jenkinsslavecentos2
INFO: [mynode] Using Chef server: https://mychef/organizations/myorg
INFO: [mynode] Using private key: /etc/chef/client.pem
INFO: [mynode] Using org name: myorg
INFO: [mynode] Incarnation ID: 79d53f1d-e9e6-4211-bc76-887851215a5b
INFO: [mynode] Starting client ...
INFO: [mynode] Retrieving configuration from https://mychef/organizations/virtu/pushy/config/jenkinsslavecentos2 ...
INFO: HTTP Request Returned 400 Bad Request: error
/opt/opscode-push-jobs-client/embedded/lib/ruby/1.9.1/net/http.rb:2633:in `error!': 400 "Bad Request" (Net::HTTPServerException)
        from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/http.rb:143:in `request'
        from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/rest.rb:115:in `get'
        from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client.rb:172:in `get_config'
        from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client.rb:72:in `start'
        from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/cli.rb:114:in `run_application'
        from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/application.rb:67:in `run'
        from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/bin/pushy-client:8:in `<top (required)>'
        from /opt/opscode-push-jobs-client/bin/pushy-client:23:in `load'
        from /opt/opscode-push-jobs-client/bin/pushy-client:23:in `<main>'

```
Pedant's run of Push Jobs Server gives no errors but shows this:
```
Pending:
  pushy config access control with pushy_job groups GET /config/<name> with pushy_job_readers returns a 200 ("OK") for member client
    # something weird going on for clients here
    # ./spec/pushy/integration/config_spec.rb:288
  pushy config access control with pushy_job groups GET /config/<name> with pushy_job_readers returns a 403 ("Forbidden") for non-member client
    # something weird going on for clients here
    # ./spec/pushy/integration/config_spec.rb:298
  pushy config handling authentication headers GET /config/<name> with successful user missing X-Ops-Userid returns 400
    # No reason given
    # /opt/opscode-push-jobs-server/embedded/service/gem/ruby/2.1.0/bundler/gems/chef-server-c1e670513e12/oc-chef-pedant/lib/pedant/rspec/auth_headers_util.rb:135
  pushy config handling authentication headers GET /config/<name> with successful user empty X-Ops-Userid returns 400
    # No reason given
    # /opt/opscode-push-jobs-server/embedded/service/gem/ruby/2.1.0/bundler/gems/chef-server-c1e670513e12/oc-chef-pedant/lib/pedant/rspec/auth_headers_util.rb:135
  pushy config handling authentication headers GET /config/<name> with successful user absolutely immense X-Ops-Userid returns 401
    # No reason given
    # /opt/opscode-push-jobs-server/embedded/service/gem/ruby/2.1.0/bundler/gems/chef-server-c1e670513e12/oc-chef-pedant/lib/pedant/rspec/auth_headers_util.rb:135
  pushy config handling authentication headers GET /config/<name> when X-Ops-Request-Source is web impersonating successful user succeeds
    # no webui_key defined in pedant config
    # /opt/opscode-push-jobs-server/embedded/service/gem/ruby/2.1.0/bundler/gems/chef-server-c1e670513e12/oc-chef-pedant/lib/pedant/rspec/auth_headers_util.rb:314
  pushy config handling authentication headers GET /config/<name> when X-Ops-Request-Source is web impersonating failed user fails
    # no webui_key defined in pedant config
    # /opt/opscode-push-jobs-server/embedded/service/gem/ruby/2.1.0/bundler/gems/chef-server-c1e670513e12/oc-chef-pedant/lib/pedant/rspec/auth_headers_util.rb:321
  end-to-end-test when one client is running a long running job and the server goes down and comes back up the client should abort and then be able to run another job, a                  nd the job should be set to crashed
    # No reason given
    # ./spec/pushy/integration/end_to_end_spec.rb:1112
  Jobs API Endpoint request error checking handling authentication headers GET /jobs with successful user with everything correct is successful
    # No reason given
    # /opt/opscode-push-jobs-server/embedded/service/gem/ruby/2.1.0/bundler/gems/chef-server-c1e670513e12/oc-chef-pedant/lib/pedant/rspec/auth_headers_util.rb:145
  Jobs API Endpoint request error checking handling authentication headers GET /jobs with successful user missing X-Ops-Sign returns 400
    # No reason given
    # /opt/opscode-push-jobs-server/embedded/service/gem/ruby/2.1.0/bundler/gems/chef-server-c1e670513e12/oc-chef-pedant/lib/pedant/rspec/auth_headers_util.rb:135
  Jobs API Endpoint request error checking handling authentication headers GET /jobs with successful user unsupported X-Ops-Sign version returns 400
    # No reason given
    # /opt/opscode-push-jobs-server/embedded/service/gem/ruby/2.1.0/bundler/gems/chef-server-c1e670513e12/oc-chef-pedant/lib/pedant/rspec/auth_headers_util.rb:135
```
And many more.

Chef server functions (knife functionality, running cookbooks) is fine.

Thanks!

**Comment by yolcatl** [comment]
sorry, issue definetely not for cookbook, it's for server

**Comment by Seth-Karlo** [comment]
@yolcatl I'm having the same issue, did you discover what the error with the server was?
